// This will create a "page" and run the callback when your page is navigated to.

Page("Sea Creatures", function(){ // Fill in your animal Type.

  $("img").attr("src", "http://www.sealifeweymouth.com/images/main-images/mobile-main-images/creatures-montage.jpg"); // Change img src to one of your animal image urls.

  $("h2").text("Sea Creatures"); // Change h2 text to the type of your animals.

  var seaCreatures = [ // Make an array of animals.
    {name: "Dolphin", image: "http://amazinganimalphotos.com/wp-content/uploads/2013/05/Dolphins-Reflections.png", info: "The giant squid (genus Architeuthis) is a deep-ocean dwelling squid in the family Architeuthidae. Giant squid can grow to a tremendous size due to deep-sea gigantism: recent estimates put the maximum size at 13 m (43 ft) for females and 10 m (33 ft) for males from the posterior fins to the tip of the two long tentacles (second only to the colossal squid at an estimated 14 m (46 ft),[2] one of the largest living organisms). The number of different giant squid species has been debated, but recent genetic research suggests that only one species exists.[3]"}, // Fill in the name, info, and image url.
    {name: "Great White Shark", image: "http://amazinganimalphotos.com/wp-content/uploads/2013/05/Great-White-Shark.jpg", info: "The great white shark (Carcharodon carcharias), also known as the great white, white pointer, white shark, or white death, is a species of large lamniform shark which can be found in the coastal surface waters of all the major oceans. The great white shark is mainly known for its size, with mature individuals growing up to 6.4 m (21 ft) in length (although reports have been published of great white sharks measuring over 8 m (26 ft))[3] and 3,324 kg (7,328 lb) in weight"},
    {name: "Killer Whale", image: "http://i1.mirror.co.uk/incoming/article3012446.ece/ALTERNATES/s615/Killer-Whale.jpg", info: "The killer whale or orca (Orcinus orca) is a toothed whale belonging to the oceanic dolphin family, of which it is the largest member. Killer whales are found in all oceans, from Arctic and Antarctic regions to tropical seas. Killer whales have a diverse diet, although individual populations often specialize in particular types of prey. Some feed exclusively on fish, while others hunt marine mammals such as seals and dolphins. They have been known to attack baleen whale calves, and even adult whales. Killer whales are apex predators, as there is no animal which preys on them."}, // Make anywhere between 3 and 9 animals.
    {name: "Darth Vader Jellyfish (Bathykorus)", image: "http://oddstuffmagazine.com/wp-content/uploads/2011/11/darthvader.jpg", info: "Found in the Arctic, this is a fairly new discovered species with 4 tentacles and 12 stomach pouches. It swims holding out its poisoned tentacles in front, better to ambush prey."},
    {name: "Giant Squid", image: "http://images.natureworldnews.com/data/thumbs/full/19911/600/0/0/0/giant-squid.jpg", info: "Bathykorus bouilloni is a species of jellyfish first described in 2010. It is a deep-sea species found in the Arctic Ocean, and seems to be common below about 1,000 m (3,300 ft).[3] It is the only species in its genus, Bathykorus.[2] The genus name comes from the Greek bathy meaning 'deep' and korus meaning 'helmet', referring to the depth at which this species is found and to the shape of the bell. It's helmet-like appearance bears a resemblance to the helmet of Darth vader, giving it the nickname Darth vader jellyfish. The specific name is in honour of Dr. Jean Bouillon, (1926–2009), a marine zoologist.[4]"},
    {name: "Hammerhead Shark", image: "http://amazinganimalphotos.com/wp-content/uploads/2013/05/Hammerhead.png", info: "The hammerhead sharks are a group of sharks in the family Sphyrnidae, so named for the unusual and distinctive structure of their heads, which are flattened and laterally extended into a 'hammer' shape called a cephalofoil. Most hammerhead species are placed in the genus Sphyrna while the winghead shark is placed in its own genus, Eusphyra. Many not necessarily mutually exclusive functions have been proposed for the cephalofoil, including sensory reception, maneuvering, and prey manipulation. Hammerheads are found worldwide in warmer waters along coastlines and continental shelves. Unlike most sharks, hammerheads usually swim in schools during the day, becoming solitary hunters at night."},
    {name: "Australian Sea Lion", image: "http://amazinganimalphotos.com/wp-content/uploads/2013/05/Australian-sea-lion.jpg", info: "The Australian sea lion (Neophoca cinerea) also known as the Australian sea-lion or Australian sealion, is a species of sea lion that is the only endemic pinniped in Australia.[2] It is monotypic in the genus Neophoca. These Sea-lions are sparsely distributed through Houtman Arbrolhos Islands (28°S., 114°E.) in Western Australia and The Pages Islands (35°46’S., 138°18’E) in Southern Australia. With a population estimated at around 14,730 animals, the Wildlife Conservation Act of Western Australia (1950) has listed them as “in need of special protection”. Their Conservation status is listed as endangered. These pinnipeds are specifically known for their abnormal breeding cycles, which are varied between 5 months breeding cycle and a 17-18 month aseasonal breeding cycle, compared to other pinnipeds which fit into a 12-month reproductive cycle."},
    {name: "Manta Ray", image: "http://static.ddmcdn.com/gif/blogs/6a00d8341bf67c53ef017d3ce6bb5a970c-800wi.jpg", info: "Manta rays are large rays belonging to the genus Manta. The larger species, M. birostris, reaches 7 m (23 ft 0 in) in width while the smaller, M. alfredi, reaches 5.5 m (18 ft 1 in). Both have triangular pectoral fins, horn-shaped cephalic fins and large, forward-facing mouths. They are classified among the Elasmobranchii (sharks and rays) and are placed in the family Myliobatidae (eagle rays). Mantas are found in temperate, subtropical and tropical waters. Both species are pelagic; M. birostris migrates across open oceans, singly or in groups, while M. alfredi tends to be resident and coastal."},
    {name: "Green Sea Turtle", image: "http://amazinganimalphotos.com/wp-content/uploads/2013/05/Green-Sea-Turtle-Red-Sea.jpg", info: "The green sea turtle (Chelonia mydas), also known as the green turtle, black (sea) turtle, or Pacific green turtle,[3] is a large sea turtle of the family Cheloniidae. This species is named for the green color of its fat, rather than the color of its skin or shell as most people think. These turtles shells are in fact olive to black. It is the only species in the genus Chelonia.[4] Its range extends throughout tropical and subtropical seas around the world, with two distinct populations in the Atlantic and Pacific Oceans.[5] The common name comes from the usually green fat found beneath its carapace."},
  ];

  for(var i = 0; i < seaCreatures.length; i++){ // Loop over your animals.
    addAnimal(seaCreatures[i]); // Pass each animal object into the addAnimal function.
  }

});
